//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidatosWeb.ServiceUbigeo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Departamento", Namespace="http://schemas.datacontract.org/2004/07/CandidatosWCF")]
    [System.SerializableAttribute()]
    public partial class Departamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomDepartamentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idDepartamento {
            get {
                return this.idDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.idDepartamentoField, value) != true)) {
                    this.idDepartamentoField = value;
                    this.RaisePropertyChanged("idDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomDepartamento {
            get {
                return this.nomDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.nomDepartamentoField, value) != true)) {
                    this.nomDepartamentoField = value;
                    this.RaisePropertyChanged("nomDepartamento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Provincia", Namespace="http://schemas.datacontract.org/2004/07/CandidatosWCF")]
    [System.SerializableAttribute()]
    public partial class Provincia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomProvinciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idProvincia {
            get {
                return this.idProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.idProvinciaField, value) != true)) {
                    this.idProvinciaField = value;
                    this.RaisePropertyChanged("idProvincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomProvincia {
            get {
                return this.nomProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.nomProvinciaField, value) != true)) {
                    this.nomProvinciaField = value;
                    this.RaisePropertyChanged("nomProvincia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Distrito", Namespace="http://schemas.datacontract.org/2004/07/CandidatosWCF")]
    [System.SerializableAttribute()]
    public partial class Distrito : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomDistritoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idDistrito {
            get {
                return this.idDistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.idDistritoField, value) != true)) {
                    this.idDistritoField = value;
                    this.RaisePropertyChanged("idDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomDistrito {
            get {
                return this.nomDistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.nomDistritoField, value) != true)) {
                    this.nomDistritoField = value;
                    this.RaisePropertyChanged("nomDistrito");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUbigeo.IServicioUbigeo")]
    public interface IServicioUbigeo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetDepartamentos", ReplyAction="http://tempuri.org/IServicioUbigeo/GetDepartamentosResponse")]
        CandidatosWeb.ServiceUbigeo.Departamento[] GetDepartamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetDepartamentos", ReplyAction="http://tempuri.org/IServicioUbigeo/GetDepartamentosResponse")]
        System.Threading.Tasks.Task<CandidatosWeb.ServiceUbigeo.Departamento[]> GetDepartamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetProvincias", ReplyAction="http://tempuri.org/IServicioUbigeo/GetProvinciasResponse")]
        CandidatosWeb.ServiceUbigeo.Provincia[] GetProvincias(string idDepa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetProvincias", ReplyAction="http://tempuri.org/IServicioUbigeo/GetProvinciasResponse")]
        System.Threading.Tasks.Task<CandidatosWeb.ServiceUbigeo.Provincia[]> GetProvinciasAsync(string idDepa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetDistritos", ReplyAction="http://tempuri.org/IServicioUbigeo/GetDistritosResponse")]
        CandidatosWeb.ServiceUbigeo.Distrito[] GetDistritos(string idDepa, string idProv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetDistritos", ReplyAction="http://tempuri.org/IServicioUbigeo/GetDistritosResponse")]
        System.Threading.Tasks.Task<CandidatosWeb.ServiceUbigeo.Distrito[]> GetDistritosAsync(string idDepa, string idProv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/ObtenerUbigeo", ReplyAction="http://tempuri.org/IServicioUbigeo/ObtenerUbigeoResponse")]
        string ObtenerUbigeo(string idDepa, string idProv, string idDist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/ObtenerUbigeo", ReplyAction="http://tempuri.org/IServicioUbigeo/ObtenerUbigeoResponse")]
        System.Threading.Tasks.Task<string> ObtenerUbigeoAsync(string idDepa, string idProv, string idDist);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUbigeoChannel : CandidatosWeb.ServiceUbigeo.IServicioUbigeo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUbigeoClient : System.ServiceModel.ClientBase<CandidatosWeb.ServiceUbigeo.IServicioUbigeo>, CandidatosWeb.ServiceUbigeo.IServicioUbigeo {
        
        public ServicioUbigeoClient() {
        }
        
        public ServicioUbigeoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioUbigeoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUbigeoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUbigeoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CandidatosWeb.ServiceUbigeo.Departamento[] GetDepartamentos() {
            return base.Channel.GetDepartamentos();
        }
        
        public System.Threading.Tasks.Task<CandidatosWeb.ServiceUbigeo.Departamento[]> GetDepartamentosAsync() {
            return base.Channel.GetDepartamentosAsync();
        }
        
        public CandidatosWeb.ServiceUbigeo.Provincia[] GetProvincias(string idDepa) {
            return base.Channel.GetProvincias(idDepa);
        }
        
        public System.Threading.Tasks.Task<CandidatosWeb.ServiceUbigeo.Provincia[]> GetProvinciasAsync(string idDepa) {
            return base.Channel.GetProvinciasAsync(idDepa);
        }
        
        public CandidatosWeb.ServiceUbigeo.Distrito[] GetDistritos(string idDepa, string idProv) {
            return base.Channel.GetDistritos(idDepa, idProv);
        }
        
        public System.Threading.Tasks.Task<CandidatosWeb.ServiceUbigeo.Distrito[]> GetDistritosAsync(string idDepa, string idProv) {
            return base.Channel.GetDistritosAsync(idDepa, idProv);
        }
        
        public string ObtenerUbigeo(string idDepa, string idProv, string idDist) {
            return base.Channel.ObtenerUbigeo(idDepa, idProv, idDist);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerUbigeoAsync(string idDepa, string idProv, string idDist) {
            return base.Channel.ObtenerUbigeoAsync(idDepa, idProv, idDist);
        }
    }
}
