//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidatosWeb.ServiceEstudio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlumnoCursoBE", Namespace="http://schemas.datacontract.org/2004/07/CandidatosWCF")]
    [System.SerializableAttribute()]
    public partial class AlumnoCursoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentariosProfesorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescActField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfesorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemaActField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoNotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloActField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeAlumno {
            get {
                return this.ApeAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeAlumnoField, value) != true)) {
                    this.ApeAlumnoField = value;
                    this.RaisePropertyChanged("ApeAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComentariosProfesor {
            get {
                return this.ComentariosProfesorField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentariosProfesorField, value) != true)) {
                    this.ComentariosProfesorField = value;
                    this.RaisePropertyChanged("ComentariosProfesor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Curso {
            get {
                return this.CursoField;
            }
            set {
                if ((object.ReferenceEquals(this.CursoField, value) != true)) {
                    this.CursoField = value;
                    this.RaisePropertyChanged("Curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescAct {
            get {
                return this.DescActField;
            }
            set {
                if ((object.ReferenceEquals(this.DescActField, value) != true)) {
                    this.DescActField = value;
                    this.RaisePropertyChanged("DescAct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombAlumno {
            get {
                return this.NombAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombAlumnoField, value) != true)) {
                    this.NombAlumnoField = value;
                    this.RaisePropertyChanged("NombAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Nota {
            get {
                return this.NotaField;
            }
            set {
                if ((this.NotaField.Equals(value) != true)) {
                    this.NotaField = value;
                    this.RaisePropertyChanged("Nota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Profesor {
            get {
                return this.ProfesorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfesorField, value) != true)) {
                    this.ProfesorField = value;
                    this.RaisePropertyChanged("Profesor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemaAct {
            get {
                return this.TemaActField;
            }
            set {
                if ((object.ReferenceEquals(this.TemaActField, value) != true)) {
                    this.TemaActField = value;
                    this.RaisePropertyChanged("TemaAct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoNota {
            get {
                return this.TipoNotaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoNotaField, value) != true)) {
                    this.TipoNotaField = value;
                    this.RaisePropertyChanged("TipoNota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TituloAct {
            get {
                return this.TituloActField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloActField, value) != true)) {
                    this.TituloActField = value;
                    this.RaisePropertyChanged("TituloAct");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlumnoPorcInasistenciaBE", Namespace="http://schemas.datacontract.org/2004/07/CandidatosWCF")]
    [System.SerializableAttribute()]
    public partial class AlumnoPorcInasistenciaBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PorcInasistField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeAlumno {
            get {
                return this.ApeAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeAlumnoField, value) != true)) {
                    this.ApeAlumnoField = value;
                    this.RaisePropertyChanged("ApeAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombAlumno {
            get {
                return this.NombAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombAlumnoField, value) != true)) {
                    this.NombAlumnoField = value;
                    this.RaisePropertyChanged("NombAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PorcInasist {
            get {
                return this.PorcInasistField;
            }
            set {
                if ((object.ReferenceEquals(this.PorcInasistField, value) != true)) {
                    this.PorcInasistField = value;
                    this.RaisePropertyChanged("PorcInasist");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlumnoCursoPromBE", Namespace="http://schemas.datacontract.org/2004/07/CandidatosWCF")]
    [System.SerializableAttribute()]
    public partial class AlumnoCursoPromBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CantClasesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CantInasistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ExaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ExaParcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfesorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PromEpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PromUaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeAlumno {
            get {
                return this.ApeAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeAlumnoField, value) != true)) {
                    this.ApeAlumnoField = value;
                    this.RaisePropertyChanged("ApeAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CantClases {
            get {
                return this.CantClasesField;
            }
            set {
                if ((this.CantClasesField.Equals(value) != true)) {
                    this.CantClasesField = value;
                    this.RaisePropertyChanged("CantClases");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CantInasist {
            get {
                return this.CantInasistField;
            }
            set {
                if ((this.CantInasistField.Equals(value) != true)) {
                    this.CantInasistField = value;
                    this.RaisePropertyChanged("CantInasist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Curso {
            get {
                return this.CursoField;
            }
            set {
                if ((object.ReferenceEquals(this.CursoField, value) != true)) {
                    this.CursoField = value;
                    this.RaisePropertyChanged("Curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ExaFin {
            get {
                return this.ExaFinField;
            }
            set {
                if ((this.ExaFinField.Equals(value) != true)) {
                    this.ExaFinField = value;
                    this.RaisePropertyChanged("ExaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ExaParc {
            get {
                return this.ExaParcField;
            }
            set {
                if ((this.ExaParcField.Equals(value) != true)) {
                    this.ExaParcField = value;
                    this.RaisePropertyChanged("ExaParc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombAlumno {
            get {
                return this.NombAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombAlumnoField, value) != true)) {
                    this.NombAlumnoField = value;
                    this.RaisePropertyChanged("NombAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Profesor {
            get {
                return this.ProfesorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfesorField, value) != true)) {
                    this.ProfesorField = value;
                    this.RaisePropertyChanged("Profesor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short PromEp {
            get {
                return this.PromEpField;
            }
            set {
                if ((this.PromEpField.Equals(value) != true)) {
                    this.PromEpField = value;
                    this.RaisePropertyChanged("PromEp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short PromUa {
            get {
                return this.PromUaField;
            }
            set {
                if ((this.PromUaField.Equals(value) != true)) {
                    this.PromUaField = value;
                    this.RaisePropertyChanged("PromUa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEstudio.IServicioEstudio")]
    public interface IServicioEstudio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudio/ConsultarNotasAlumno", ReplyAction="http://tempuri.org/IServicioEstudio/ConsultarNotasAlumnoResponse")]
        CandidatosWeb.ServiceEstudio.AlumnoCursoBE[] ConsultarNotasAlumno(string mvarDni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudio/ConsultarNotasAlumno", ReplyAction="http://tempuri.org/IServicioEstudio/ConsultarNotasAlumnoResponse")]
        System.Threading.Tasks.Task<CandidatosWeb.ServiceEstudio.AlumnoCursoBE[]> ConsultarNotasAlumnoAsync(string mvarDni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudio/ConsultarPorcentajeInasistenciaAlumno", ReplyAction="http://tempuri.org/IServicioEstudio/ConsultarPorcentajeInasistenciaAlumnoResponse" +
            "")]
        CandidatosWeb.ServiceEstudio.AlumnoPorcInasistenciaBE[] ConsultarPorcentajeInasistenciaAlumno(string mvarDni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudio/ConsultarPorcentajeInasistenciaAlumno", ReplyAction="http://tempuri.org/IServicioEstudio/ConsultarPorcentajeInasistenciaAlumnoResponse" +
            "")]
        System.Threading.Tasks.Task<CandidatosWeb.ServiceEstudio.AlumnoPorcInasistenciaBE[]> ConsultarPorcentajeInasistenciaAlumnoAsync(string mvarDni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudio/ConsultarPromedioPorCursoAlumno", ReplyAction="http://tempuri.org/IServicioEstudio/ConsultarPromedioPorCursoAlumnoResponse")]
        CandidatosWeb.ServiceEstudio.AlumnoCursoPromBE[] ConsultarPromedioPorCursoAlumno(string mvarDni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudio/ConsultarPromedioPorCursoAlumno", ReplyAction="http://tempuri.org/IServicioEstudio/ConsultarPromedioPorCursoAlumnoResponse")]
        System.Threading.Tasks.Task<CandidatosWeb.ServiceEstudio.AlumnoCursoPromBE[]> ConsultarPromedioPorCursoAlumnoAsync(string mvarDni);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEstudioChannel : CandidatosWeb.ServiceEstudio.IServicioEstudio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEstudioClient : System.ServiceModel.ClientBase<CandidatosWeb.ServiceEstudio.IServicioEstudio>, CandidatosWeb.ServiceEstudio.IServicioEstudio {
        
        public ServicioEstudioClient() {
        }
        
        public ServicioEstudioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEstudioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEstudioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEstudioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CandidatosWeb.ServiceEstudio.AlumnoCursoBE[] ConsultarNotasAlumno(string mvarDni) {
            return base.Channel.ConsultarNotasAlumno(mvarDni);
        }
        
        public System.Threading.Tasks.Task<CandidatosWeb.ServiceEstudio.AlumnoCursoBE[]> ConsultarNotasAlumnoAsync(string mvarDni) {
            return base.Channel.ConsultarNotasAlumnoAsync(mvarDni);
        }
        
        public CandidatosWeb.ServiceEstudio.AlumnoPorcInasistenciaBE[] ConsultarPorcentajeInasistenciaAlumno(string mvarDni) {
            return base.Channel.ConsultarPorcentajeInasistenciaAlumno(mvarDni);
        }
        
        public System.Threading.Tasks.Task<CandidatosWeb.ServiceEstudio.AlumnoPorcInasistenciaBE[]> ConsultarPorcentajeInasistenciaAlumnoAsync(string mvarDni) {
            return base.Channel.ConsultarPorcentajeInasistenciaAlumnoAsync(mvarDni);
        }
        
        public CandidatosWeb.ServiceEstudio.AlumnoCursoPromBE[] ConsultarPromedioPorCursoAlumno(string mvarDni) {
            return base.Channel.ConsultarPromedioPorCursoAlumno(mvarDni);
        }
        
        public System.Threading.Tasks.Task<CandidatosWeb.ServiceEstudio.AlumnoCursoPromBE[]> ConsultarPromedioPorCursoAlumnoAsync(string mvarDni) {
            return base.Channel.ConsultarPromedioPorCursoAlumnoAsync(mvarDni);
        }
    }
}
