//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidatosWCF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CandidatosIsilEntities : DbContext
    {
        public CandidatosIsilEntities()
            : base("name=CandidatosIsilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Actividad> Tb_Actividad { get; set; }
        public virtual DbSet<Tb_Actividad_Asignada> Tb_Actividad_Asignada { get; set; }
        public virtual DbSet<Tb_Actividad_Extra> Tb_Actividad_Extra { get; set; }
        public virtual DbSet<Tb_Alumno> Tb_Alumno { get; set; }
        public virtual DbSet<Tb_Carrera> Tb_Carrera { get; set; }
        public virtual DbSet<Tb_Ciclo> Tb_Ciclo { get; set; }
        public virtual DbSet<Tb_Consejero> Tb_Consejero { get; set; }
        public virtual DbSet<Tb_Coordinador> Tb_Coordinador { get; set; }
        public virtual DbSet<Tb_Curso> Tb_Curso { get; set; }
        public virtual DbSet<Tb_Curso_Programado> Tb_Curso_Programado { get; set; }
        public virtual DbSet<Tb_Estudio> Tb_Estudio { get; set; }
        public virtual DbSet<Tb_Facultad> Tb_Facultad { get; set; }
        public virtual DbSet<Tb_Laboratorio> Tb_Laboratorio { get; set; }
        public virtual DbSet<Tb_Ocurrencias> Tb_Ocurrencias { get; set; }
        public virtual DbSet<Tb_Profesor> Tb_Profesor { get; set; }
        public virtual DbSet<Tb_Registro_Usuario> Tb_Registro_Usuario { get; set; }
        public virtual DbSet<Tb_Rol> Tb_Rol { get; set; }
        public virtual DbSet<Tb_Sede> Tb_Sede { get; set; }
        public virtual DbSet<Tb_Seleccion_Act_Extra> Tb_Seleccion_Act_Extra { get; set; }
        public virtual DbSet<Tb_Tipo_Nota> Tb_Tipo_Nota { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
    
        public virtual ObjectResult<usp_AlumnoNotasDni_Result> usp_AlumnoNotasDni(string vdni)
        {
            var vdniParameter = vdni != null ?
                new ObjectParameter("vdni", vdni) :
                new ObjectParameter("vdni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AlumnoNotasDni_Result>("usp_AlumnoNotasDni", vdniParameter);
        }
    
        public virtual ObjectResult<usp_AlumnoOcurrencias_Result> usp_AlumnoOcurrencias(string vdni)
        {
            var vdniParameter = vdni != null ?
                new ObjectParameter("vdni", vdni) :
                new ObjectParameter("vdni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AlumnoOcurrencias_Result>("usp_AlumnoOcurrencias", vdniParameter);
        }
    
        public virtual ObjectResult<usp_AlumnoPorcInasistDni_Result> usp_AlumnoPorcInasistDni(string vdni)
        {
            var vdniParameter = vdni != null ?
                new ObjectParameter("vdni", vdni) :
                new ObjectParameter("vdni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AlumnoPorcInasistDni_Result>("usp_AlumnoPorcInasistDni", vdniParameter);
        }
    
        public virtual ObjectResult<usp_AlumnoPromedioCursoDni_Result> usp_AlumnoPromedioCursoDni(string vdni)
        {
            var vdniParameter = vdni != null ?
                new ObjectParameter("vdni", vdni) :
                new ObjectParameter("vdni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AlumnoPromedioCursoDni_Result>("usp_AlumnoPromedioCursoDni", vdniParameter);
        }
    }
}
