//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidatosWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Alumno()
        {
            this.Tb_Actividad_Asignada = new HashSet<Tb_Actividad_Asignada>();
            this.Tb_Estudio = new HashSet<Tb_Estudio>();
            this.Tb_Ocurrencias = new HashSet<Tb_Ocurrencias>();
            this.Tb_Seleccion_Act_Extra = new HashSet<Tb_Seleccion_Act_Extra>();
        }
    
        public int id_alumno { get; set; }
        public Nullable<int> id_consejero { get; set; }
        public string dni_alumno { get; set; }
        public string nomb_alumno { get; set; }
        public string ape_alumno { get; set; }
        public string ubi_alumno { get; set; }
        public string tel_alumno { get; set; }
        public string email_alumno { get; set; }
        public System.DateTime fec_inscrip { get; set; }
        public Nullable<double> prom_global { get; set; }
        public int status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Actividad_Asignada> Tb_Actividad_Asignada { get; set; }
        public virtual Tb_Consejero Tb_Consejero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Estudio> Tb_Estudio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Ocurrencias> Tb_Ocurrencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Seleccion_Act_Extra> Tb_Seleccion_Act_Extra { get; set; }
    }
}
