//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidatosWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Actividad_Asignada
    {
        public int id_actividad { get; set; }
        public int id_alumno { get; set; }
        public int id_curso_prog { get; set; }
        public Nullable<int> id_tipo_nota { get; set; }
        public System.DateTime fec_ini { get; set; }
        public Nullable<System.DateTime> fec_entrega { get; set; }
        public Nullable<int> nota_act { get; set; }
        public string coment_prof { get; set; }
        public int status { get; set; }
    
        public virtual Tb_Actividad Tb_Actividad { get; set; }
        public virtual Tb_Alumno Tb_Alumno { get; set; }
        public virtual Tb_Curso_Programado Tb_Curso_Programado { get; set; }
        public virtual Tb_Tipo_Nota Tb_Tipo_Nota { get; set; }
    }
}
