//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidatosWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Actividad_Extra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Actividad_Extra()
        {
            this.Tb_Seleccion_Act_Extra = new HashSet<Tb_Seleccion_Act_Extra>();
        }
    
        public int id_actividad_ext { get; set; }
        public string titulo_act_ext { get; set; }
        public string tema_act_ext { get; set; }
        public string desc_act_ext { get; set; }
        public int status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Seleccion_Act_Extra> Tb_Seleccion_Act_Extra { get; set; }
    }
}
