//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidatosWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Consejero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Consejero()
        {
            this.Tb_Alumno = new HashSet<Tb_Alumno>();
        }
    
        public int id_consejero { get; set; }
        public int id_sede { get; set; }
        public string dni_consejero { get; set; }
        public string nomb_consejero { get; set; }
        public string ape_consejero { get; set; }
        public string ubi_consejero { get; set; }
        public string tel_consejero { get; set; }
        public string email_consejero { get; set; }
        public int status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Alumno> Tb_Alumno { get; set; }
        public virtual Tb_Sede Tb_Sede { get; set; }
    }
}
