//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidatosWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Ciclo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Ciclo()
        {
            this.Tb_Curso_Programado = new HashSet<Tb_Curso_Programado>();
        }
    
        public int id_ciclo { get; set; }
        public System.DateTime fec_inicio_ciclo { get; set; }
        public System.DateTime fec_fin_ciclo { get; set; }
        public Nullable<int> num_fer_prog_ciclo { get; set; }
        public int status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Curso_Programado> Tb_Curso_Programado { get; set; }
    }
}
