//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidatosWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Curso_Programado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Curso_Programado()
        {
            this.Tb_Actividad_Asignada = new HashSet<Tb_Actividad_Asignada>();
            this.Tb_Estudio = new HashSet<Tb_Estudio>();
        }
    
        public int id_curso_prog { get; set; }
        public Nullable<int> id_laboratorio { get; set; }
        public int id_curso { get; set; }
        public int id_profesor { get; set; }
        public int id_ciclo { get; set; }
        public Nullable<int> num_horas { get; set; }
        public int cant_clases { get; set; }
        public int status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Actividad_Asignada> Tb_Actividad_Asignada { get; set; }
        public virtual Tb_Ciclo Tb_Ciclo { get; set; }
        public virtual Tb_Curso Tb_Curso { get; set; }
        public virtual Tb_Laboratorio Tb_Laboratorio { get; set; }
        public virtual Tb_Profesor Tb_Profesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Estudio> Tb_Estudio { get; set; }
    }
}
