//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidatosWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Curso()
        {
            this.Tb_Curso_Programado = new HashSet<Tb_Curso_Programado>();
            this.Tb_Curso1 = new HashSet<Tb_Curso>();
        }
    
        public int id_curso { get; set; }
        public Nullable<int> id_carrera { get; set; }
        public Nullable<int> id_pre_req_curso { get; set; }
        public string desc_curso { get; set; }
        public Nullable<System.DateTime> fec_crea { get; set; }
        public int status { get; set; }
    
        public virtual Tb_Carrera Tb_Carrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Curso_Programado> Tb_Curso_Programado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Curso> Tb_Curso1 { get; set; }
        public virtual Tb_Curso Tb_Curso2 { get; set; }
    }
}
