//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidatosWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Laboratorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Laboratorio()
        {
            this.Tb_Curso_Programado = new HashSet<Tb_Curso_Programado>();
        }
    
        public int id_laboratorio { get; set; }
        public Nullable<int> id_sede { get; set; }
        public string bloque_lab { get; set; }
        public int num_lab { get; set; }
        public int aforo_lab { get; set; }
        public int status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Curso_Programado> Tb_Curso_Programado { get; set; }
        public virtual Tb_Sede Tb_Sede { get; set; }
    }
}
