//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidatosWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Seleccion_Act_Extra
    {
        public int id_actividad_ext { get; set; }
        public int id_alumno { get; set; }
        public System.DateTime fec_ini { get; set; }
        public Nullable<System.DateTime> fec_fin { get; set; }
        public int status { get; set; }
    
        public virtual Tb_Actividad_Extra Tb_Actividad_Extra { get; set; }
        public virtual Tb_Alumno Tb_Alumno { get; set; }
    }
}
