//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidatosWeb.ServiceAlumno {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlumnoBE", Namespace="http://schemas.datacontract.org/2004/07/CandidatosWCF")]
    [System.SerializableAttribute()]
    public partial class AlumnoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecInscripField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PromGlobalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbiAlumnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeAlumno {
            get {
                return this.ApeAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeAlumnoField, value) != true)) {
                    this.ApeAlumnoField = value;
                    this.RaisePropertyChanged("ApeAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DniAlumno {
            get {
                return this.DniAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.DniAlumnoField, value) != true)) {
                    this.DniAlumnoField = value;
                    this.RaisePropertyChanged("DniAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAlumno {
            get {
                return this.EmailAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAlumnoField, value) != true)) {
                    this.EmailAlumnoField = value;
                    this.RaisePropertyChanged("EmailAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecInscrip {
            get {
                return this.FecInscripField;
            }
            set {
                if ((this.FecInscripField.Equals(value) != true)) {
                    this.FecInscripField = value;
                    this.RaisePropertyChanged("FecInscrip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombAlumno {
            get {
                return this.NombAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombAlumnoField, value) != true)) {
                    this.NombAlumnoField = value;
                    this.RaisePropertyChanged("NombAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PromGlobal {
            get {
                return this.PromGlobalField;
            }
            set {
                if ((this.PromGlobalField.Equals(value) != true)) {
                    this.PromGlobalField = value;
                    this.RaisePropertyChanged("PromGlobal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelAlumno {
            get {
                return this.TelAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelAlumnoField, value) != true)) {
                    this.TelAlumnoField = value;
                    this.RaisePropertyChanged("TelAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UbiAlumno {
            get {
                return this.UbiAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.UbiAlumnoField, value) != true)) {
                    this.UbiAlumnoField = value;
                    this.RaisePropertyChanged("UbiAlumno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlumnoOcurrenciaBE", Namespace="http://schemas.datacontract.org/2004/07/CandidatosWCF")]
    [System.SerializableAttribute()]
    public partial class AlumnoOcurrenciaBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescOcurrenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaOcurrenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombAlumnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeAlumno {
            get {
                return this.ApeAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeAlumnoField, value) != true)) {
                    this.ApeAlumnoField = value;
                    this.RaisePropertyChanged("ApeAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescOcurrencia {
            get {
                return this.DescOcurrenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.DescOcurrenciaField, value) != true)) {
                    this.DescOcurrenciaField = value;
                    this.RaisePropertyChanged("DescOcurrencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaOcurrencia {
            get {
                return this.FechaOcurrenciaField;
            }
            set {
                if ((this.FechaOcurrenciaField.Equals(value) != true)) {
                    this.FechaOcurrenciaField = value;
                    this.RaisePropertyChanged("FechaOcurrencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombAlumno {
            get {
                return this.NombAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombAlumnoField, value) != true)) {
                    this.NombAlumnoField = value;
                    this.RaisePropertyChanged("NombAlumno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAlumno.IServicioAlumno")]
    public interface IServicioAlumno {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ConsultarAlumnoPorDni", ReplyAction="http://tempuri.org/IServicioAlumno/ConsultarAlumnoPorDniResponse")]
        CandidatosWeb.ServiceAlumno.AlumnoBE ConsultarAlumnoPorDni(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ConsultarAlumnoPorDni", ReplyAction="http://tempuri.org/IServicioAlumno/ConsultarAlumnoPorDniResponse")]
        System.Threading.Tasks.Task<CandidatosWeb.ServiceAlumno.AlumnoBE> ConsultarAlumnoPorDniAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ConsultarAlumnoPorTelefono", ReplyAction="http://tempuri.org/IServicioAlumno/ConsultarAlumnoPorTelefonoResponse")]
        CandidatosWeb.ServiceAlumno.AlumnoBE ConsultarAlumnoPorTelefono(string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ConsultarAlumnoPorTelefono", ReplyAction="http://tempuri.org/IServicioAlumno/ConsultarAlumnoPorTelefonoResponse")]
        System.Threading.Tasks.Task<CandidatosWeb.ServiceAlumno.AlumnoBE> ConsultarAlumnoPorTelefonoAsync(string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ConsultarAlumnoPorCorreo", ReplyAction="http://tempuri.org/IServicioAlumno/ConsultarAlumnoPorCorreoResponse")]
        CandidatosWeb.ServiceAlumno.AlumnoBE ConsultarAlumnoPorCorreo(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ConsultarAlumnoPorCorreo", ReplyAction="http://tempuri.org/IServicioAlumno/ConsultarAlumnoPorCorreoResponse")]
        System.Threading.Tasks.Task<CandidatosWeb.ServiceAlumno.AlumnoBE> ConsultarAlumnoPorCorreoAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ConsultarAlumnoPorNombreApellido", ReplyAction="http://tempuri.org/IServicioAlumno/ConsultarAlumnoPorNombreApellidoResponse")]
        CandidatosWeb.ServiceAlumno.AlumnoBE[] ConsultarAlumnoPorNombreApellido(string nombre, string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ConsultarAlumnoPorNombreApellido", ReplyAction="http://tempuri.org/IServicioAlumno/ConsultarAlumnoPorNombreApellidoResponse")]
        System.Threading.Tasks.Task<CandidatosWeb.ServiceAlumno.AlumnoBE[]> ConsultarAlumnoPorNombreApellidoAsync(string nombre, string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ConsultarAlumnoOcurrencias", ReplyAction="http://tempuri.org/IServicioAlumno/ConsultarAlumnoOcurrenciasResponse")]
        CandidatosWeb.ServiceAlumno.AlumnoOcurrenciaBE[] ConsultarAlumnoOcurrencias(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ConsultarAlumnoOcurrencias", ReplyAction="http://tempuri.org/IServicioAlumno/ConsultarAlumnoOcurrenciasResponse")]
        System.Threading.Tasks.Task<CandidatosWeb.ServiceAlumno.AlumnoOcurrenciaBE[]> ConsultarAlumnoOcurrenciasAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ConsultarTopCincoAlumnos", ReplyAction="http://tempuri.org/IServicioAlumno/ConsultarTopCincoAlumnosResponse")]
        CandidatosWeb.ServiceAlumno.AlumnoBE[] ConsultarTopCincoAlumnos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ConsultarTopCincoAlumnos", ReplyAction="http://tempuri.org/IServicioAlumno/ConsultarTopCincoAlumnosResponse")]
        System.Threading.Tasks.Task<CandidatosWeb.ServiceAlumno.AlumnoBE[]> ConsultarTopCincoAlumnosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioAlumnoChannel : CandidatosWeb.ServiceAlumno.IServicioAlumno, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioAlumnoClient : System.ServiceModel.ClientBase<CandidatosWeb.ServiceAlumno.IServicioAlumno>, CandidatosWeb.ServiceAlumno.IServicioAlumno {
        
        public ServicioAlumnoClient() {
        }
        
        public ServicioAlumnoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioAlumnoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAlumnoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAlumnoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CandidatosWeb.ServiceAlumno.AlumnoBE ConsultarAlumnoPorDni(string dni) {
            return base.Channel.ConsultarAlumnoPorDni(dni);
        }
        
        public System.Threading.Tasks.Task<CandidatosWeb.ServiceAlumno.AlumnoBE> ConsultarAlumnoPorDniAsync(string dni) {
            return base.Channel.ConsultarAlumnoPorDniAsync(dni);
        }
        
        public CandidatosWeb.ServiceAlumno.AlumnoBE ConsultarAlumnoPorTelefono(string telefono) {
            return base.Channel.ConsultarAlumnoPorTelefono(telefono);
        }
        
        public System.Threading.Tasks.Task<CandidatosWeb.ServiceAlumno.AlumnoBE> ConsultarAlumnoPorTelefonoAsync(string telefono) {
            return base.Channel.ConsultarAlumnoPorTelefonoAsync(telefono);
        }
        
        public CandidatosWeb.ServiceAlumno.AlumnoBE ConsultarAlumnoPorCorreo(string correo) {
            return base.Channel.ConsultarAlumnoPorCorreo(correo);
        }
        
        public System.Threading.Tasks.Task<CandidatosWeb.ServiceAlumno.AlumnoBE> ConsultarAlumnoPorCorreoAsync(string correo) {
            return base.Channel.ConsultarAlumnoPorCorreoAsync(correo);
        }
        
        public CandidatosWeb.ServiceAlumno.AlumnoBE[] ConsultarAlumnoPorNombreApellido(string nombre, string apellido) {
            return base.Channel.ConsultarAlumnoPorNombreApellido(nombre, apellido);
        }
        
        public System.Threading.Tasks.Task<CandidatosWeb.ServiceAlumno.AlumnoBE[]> ConsultarAlumnoPorNombreApellidoAsync(string nombre, string apellido) {
            return base.Channel.ConsultarAlumnoPorNombreApellidoAsync(nombre, apellido);
        }
        
        public CandidatosWeb.ServiceAlumno.AlumnoOcurrenciaBE[] ConsultarAlumnoOcurrencias(string dni) {
            return base.Channel.ConsultarAlumnoOcurrencias(dni);
        }
        
        public System.Threading.Tasks.Task<CandidatosWeb.ServiceAlumno.AlumnoOcurrenciaBE[]> ConsultarAlumnoOcurrenciasAsync(string dni) {
            return base.Channel.ConsultarAlumnoOcurrenciasAsync(dni);
        }
        
        public CandidatosWeb.ServiceAlumno.AlumnoBE[] ConsultarTopCincoAlumnos() {
            return base.Channel.ConsultarTopCincoAlumnos();
        }
        
        public System.Threading.Tasks.Task<CandidatosWeb.ServiceAlumno.AlumnoBE[]> ConsultarTopCincoAlumnosAsync() {
            return base.Channel.ConsultarTopCincoAlumnosAsync();
        }
    }
}
